tor-address:
  name: Tor Address
  description: The Tor address for the main ui. 
  type: pointer
  subtype: package
  package-id: cryptpad
  target: tor-address
  interface: main
sandbox-tor-address:
  name: Tor Address
  description: The Tor address for the sandbox ui. 
  type: pointer
  subtype: package
  package-id: cryptpad
  target: tor-address
  interface: sandbox
